This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./Doku.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Doku.acn....done (138 entries accepted, 0 rejected).
Sorting entries....done (1066 comparisons).
Generating output file Doku.acr....done (93 lines written, 0 warnings).
Output written in Doku.acr.
Transcript written in Doku.alg.
